language: c++
os:
  - windows
  - linux
  - osx
compiler:
  - clang
  - gcc
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y \
      && sudo apt-get update -qq \
      && if [ "$CXX" == "g++" ]; then
        sudo apt-get install -qq g++-4.7 && export CXX="g++-4.7" CC="gcc-4.7"
      fi
    fi
before_script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install visualstudio2017-workload-nativedesktop
    fi
  - mkdir build
  - cd build
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cmake .. -GNinja  -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64
    else
      cmake ..
    fi

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cmake --build . --config Release
    else
      make
    fi
  - test/run-tests

matrix:
  exclude:
  - os: linux
    compiler: clang
